name: Update TOC Interface version(s)

on:
  workflow_dispatch:
  schedule:
    - cron: 0 20 * * 2

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v4

      - name: Update TOC Interface version
        uses: p3lim/toc-interface-updater@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Update Interface version
          branch: bump-version
          delete-branch: true
          assignees: tomill
